---
title: "Pilot_96_combinations_with_66strains"
author: "KiseokUchicago"
date: "2021-07-27"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## Pilot experiment: Pilot_96_combinations_with_66strains
Confirm Rita's 96 combinations and compare with null.
96 combinations would be in Gaussian distribution (mean 20, max 40, min 2)
**Kiseok Lee** 
PI: **Seppe Kuehn**, **Arjun Raman**


```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(picante)
library(fields)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))
  
mytheme_2d <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
   "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# functions
plot_UMAP <- function(df_Biobank){
  ggplot(df_Biobank, aes(x=umapA1, y=umapA2)) +
    xlab('\n umap A1')+
    ylab("umap A2 \n") +
    geom_point(aes(fill = genus), shape = 21 ,size=4, alpha=0.9) +
    scale_fill_manual(values = my_color_collection)+
    ggtitle(paste0("UMAP coordination"," \n")) +
    # scale_x_continuous(limits = c(0, max(df_cen_wb$Degree))) +
    # scale_y_continuous(limits = c(0, max(df_cen_wb$Betweenness))) +
    theme(legend.text=element_text(size=13)) + 
    # theme(legend.position="top") +
    # theme(legend.title=element_blank()) +
    guides(colour = guide_legend(override.aes = list(size=8), reverse = TRUE))+
    guides(size=FALSE) +
    mytheme_2d
}

# import tree
phy_tree <- ape::read.tree("data/Biobank_align_mafft.fasta.treefile_rooted.nwk")
phy_tree

# Import 66 strain list
strain66 <- read.xlsx('data/Strain_selected_95_max_NTI_CEKannotated_updated.xlsx')
dim(strain66)
head(strain66)
colnames(strain66)
strain66 <- strain66 %>% filter(!is.na(phy_id))

# get UMAP coordinate information
library(fields)
strain66_coor <- strain66 %>% select(phy_id, umapA1, umapA2)
strain66_coor <- tibble::column_to_rownames(strain66_coor, var="phy_id") 
strain66_dist <- rdist(strain66_coor)
dim(strain66_dist)
strain66_dist <- as.data.frame(strain66_dist)
rownames(strain66_dist) <- rownames(strain66_coor)
colnames(strain66_dist) <- rownames(strain66_coor)
head(strain66_dist)

# import database
df_Biobank <- read.csv('data/biobank.umap.16sSeqs.csv')
# how many species
df_species <- df_Biobank %>% group_by(species) %>% summarise(number=n_distinct(species))
# get id and sequence
# id is seq_id + species
phylo_Biobank <- df_Biobank %>% unite(phy_id,c("seq_id",'species'),sep="_", remove=F)
phylo_Biobank$species <- gsub("\\[","",phylo_Biobank$species)
phylo_Biobank$species <- gsub("]","",phylo_Biobank$species)
# remove space in the id for downstream
phylo_Biobank$phy_id <- gsub(" ","_",phylo_Biobank$phy_id) 
# remove "[" and "]"
phylo_Biobank$phy_id <- gsub("\\[","",phylo_Biobank$phy_id)
phylo_Biobank$phy_id <- gsub("]","",phylo_Biobank$phy_id)
col2_Biobank <- phylo_Biobank %>% dplyr::select(phy_id,nuc_sequence)
```

## Sampling function

```{r}
# randomly select n=20 different species
rand_num = 10000 # how many sampling 
n = 20 # community size

# execute function
sampling_func <- function(rand_num = 10000, n = 20, lower_percentile = 1.0){ # num_com : number of picked communities
  # empty list
  sampling20_list <- list() 
  
  # do sampling for rand_num of times
  for (rand in 1:rand_num){
    # print(rand)
    # random sampling
    strain20_rand <- sample(strain66$phy_id, n)
    strain20_coor <- strain66 %>% filter(phy_id %in% strain20_rand) %>% select(phy_id, umapA1, umapA2)
    strain20_coor <- tibble::column_to_rownames(strain20_coor, var="phy_id") 
    strain20_dist <- rdist(strain20_coor)
    dim(strain20_dist)
    strain20_dist <- as.data.frame(strain20_dist)
    rownames(strain20_dist) <- rownames(strain20_coor)
    colnames(strain20_dist) <- rownames(strain20_coor)
    head(strain20_dist)
    
    # get minimum distance (minimum positive)
    nearest_dist_vec <- apply(strain20_dist, 1, FUN = function(x) {min(x[x > 0])})
    nearest_dist_vec <- nearest_dist_vec[order(nearest_dist_vec)] # order from lowest to highest
    
    # nearest distance for lower percentile
    nearest_dist_vec[1:round(n*lower_percentile)]
    # get mean of nearest UMAP distance
    mean1 = mean(nearest_dist_vec[1:round(n*lower_percentile)])
    
    # save in list
    sampling20_list[[rand]] <- list(
      mean_nearest_distance = mean1,
      distance_mat = strain20_dist
    )
  }
  return(sampling20_list)
}

```






## Import Rita's excel sheet
Make x into 1.
```{r}
# import
df_rita <- openxlsx::read.xlsx("data/96MemberCommunities_formatted.xlsx", colNames = F)
df_rita <- as.data.frame(df_rita)

class(df_rita)
dim(df_rita)
head(df_rita)

# set rownames to species_id
rownames(df_rita) <- NULL
df_rita1 <- tibble::column_to_rownames(df_rita, var = "X1")

rownames(df_rita1)
colnames(df_rita1)

# True False matrix
df_binary <- !is.na(df_rita1)
colSums(df_binary)
table(colSums(df_binary))

# histogram of number of strains in the community
hist(colSums(df_binary), breaks =40)


# get the vector for each mix
strains_vec <- rownames(df_rita1)
dim(df_binary)
class(df_binary)

df_binary[,1]

df_binary[,1][df_binary[,1] == T]

# make a list
mix_list <- list()
for (i in 1:dim(df_binary)[2]){
  print(i)
  species <- df_binary[,i][df_binary[,i] == T]
  mix_list[[i]] <- names(species)
}
mix_list
```


## Sampling scheme
```{r}
# Gaussian distribution
set.seed(1)
rnorm_num <- round(rnorm(96,mean=24,10))
hist(rnorm_num,breaks = 50)

table(rnorm_num)

# Or Rita's distribution
table(colSums(df_binary))
```


Maximize mean nearest of lower 30% percentile.

```{r}

# function
pick_selection <- function(rand_num = 10000, n = 20, lower_percentile = 0.3){
  # Sampling
  strain20_per <- sampling_func(rand_num, n, lower_percentile)
  # Distance
  mean_nearest_dist_vec <- c()
  for (i in 1:rand_num){
    mean_nearest_dist_vec[i] <- strain20_per[[i]]$mean_nearest_distance
  }
  
  max_30 <- strain20_per[[which.max(mean_nearest_dist_vec)]]$distance_mat
  max_30strain_list <- rownames(max_30)
  strain20_30per <- phylo_Biobank %>% filter(phy_id %in% max_30strain_list)
  
  plot_UMAP(strain66 %>% filter(phy_id %in% max_30strain_list))
  return(max_30strain_list)
}


pick_selection(rand_num = 10000, n = 20, lower_percentile = 0.3)

```

# Get 96 combination
```{r}
# Or Rita's distribution
combination_vec <- table(colSums(df_binary))

# 
for (i in 1:length(combination_vec)){
  # print(i)
  com_num <- as.numeric(names(combination_vec[i]))
  replicate <- combination_vec[[i]]
  for (j in 1:replicate){
    print(j)
    pick <- pick_selection(rand_num = 100, n = com_num, lower_percentile = 0.3)
    print(pick)
  }
}






```





